[build]
  command = "pnpm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = []
  node_bundler = "esbuild"
  included_files = [".env"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[redirects]]
  from = "/app_viz_data.json"
  to = "/app_viz_data.json"
  status = 200
  force = true

[[redirects]]
  from = "/repo-details.json"
  to = "/repo-details.json"
  status = 200
  force = true

[[redirects]]
  from = "/repositories_details.json"
  to = "/repositories_details.json"
  status = 200
  force = true
